# -*- coding: utf-8 -*-
"""07.07.02 Exercícios Listas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BA-7w6uZza1l-gkiU_nn-K0VJ6n-aoFQ

# Exercícios

## 1. Faturamento do Melhor e do Pior Mês do Ano

Qual foi o valor de vendas do melhor mês do Ano?
E valor do pior mês do ano?
"""

meses = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']
vendas_1sem = [25000, 29000, 22200, 17750, 15870, 19900]
vendas_2sem = [19850, 20120, 17540, 15555, 49051, 9650]

vendas = vendas_1sem + vendas_2sem

#print(vendas)

"""## 2. Continuação

Agora relacione as duas listas para printar 'O melhor mês do ano foi {} com {} vendas' e o mesmo para o pior mês do ano.

Calcule também o faturamento total do Ano e quanto que o melhor mês representou do faturamento total.

Obs: Para o faturamento total, pode usar a função sum(lista) que soma todos os itens de uma lista
"""

mv = max(vendas)
mnv = min(vendas)
imv = vendas.index(mv)
imnv = vendas.index(mnv)
melhor_mes = meses[imv]
pior_mes = meses[imnv]
total = sum(vendas)


print(f'O pior mês do ano foi {pior_mes} com {mnv} vendas')
print(f'O melhor mês do ano foi {melhor_mes} com {mv} vendas')
print(f"No ano tivemos um total de {total} de vendas")

print()

"""## 3. Crie uma lista com o top 3 valores de vendas do ano (sem fazer "no olho")

Dica: o método remove retira um item da lista.
"""

top3 =[]

maiores_valores = max(vendas)

top3.append(maiores_valores)

vendas.remove(maiores_valores)

#

maiores_valores = max(vendas)

top3.append(maiores_valores)

vendas.remove(maiores_valores)

#

maiores_valores = max(vendas)

top3.append(maiores_valores)

vendas.remove(maiores_valores)

print(maiores_valores)
print(vendas)
print(top3)